/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe.View;

import TicTacToe.JogoCode;

/**
 *
 * @author ADMIN
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    JogoCode jogo = new JogoCode();

    public Jogo() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PontosO = new javax.swing.JLabel();
        PontosX = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();
        Posicao9 = new javax.swing.JButton();
        Posicao8 = new javax.swing.JButton();
        Posicao7 = new javax.swing.JButton();
        Posicao6 = new javax.swing.JButton();
        Posicao5 = new javax.swing.JButton();
        Posicao4 = new javax.swing.JButton();
        Posicao3 = new javax.swing.JButton();
        Posicao2 = new javax.swing.JButton();
        Posicao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PontosO.setFont(new java.awt.Font("Adigiana Toybox", 0, 18)); // NOI18N
        PontosO.setForeground(new java.awt.Color(0, 0, 0));
        PontosO.setText("0");
        jPanel1.add(PontosO, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        PontosX.setFont(new java.awt.Font("Adigiana Toybox", 0, 18)); // NOI18N
        PontosX.setForeground(new java.awt.Color(0, 0, 0));
        PontosX.setText("0");
        jPanel1.add(PontosX, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        Voltar.setText("Voltar");
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, -1));

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/Resources/TicTacJogo.png"))); // NOI18N
        jPanel1.add(Imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Posicao9.setText("jButton1");
        Posicao9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Posicao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao9ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, 60));

        Posicao8.setText("jButton1");
        Posicao8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Posicao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao8ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, 50));

        Posicao7.setText("jButton1");
        Posicao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao7ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 70, 40));

        Posicao6.setText("jButton1");
        Posicao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao6ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 70, 50));

        Posicao5.setText("jButton1");
        Posicao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao5ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 60));

        Posicao4.setText("jButton1");
        jPanel1.add(Posicao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 50));

        Posicao3.setText("jButton1");
        jPanel1.add(Posicao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 40));

        Posicao2.setText("jButton1");
        jPanel1.add(Posicao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 50));

        Posicao1.setText("jButton1");
        Posicao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Posicao1ActionPerformed(evt);
            }
        });
        jPanel1.add(Posicao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Posicao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Posicao5ActionPerformed

    private void Posicao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Posicao6ActionPerformed

    private void Posicao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Posicao7ActionPerformed

    private void Posicao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Posicao8ActionPerformed

    private void Posicao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Posicao9ActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicial i = new Inicial();
        i.setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void Posicao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Posicao1ActionPerformed
        // TODO add your handling code here:
        fim(jogo.jogada(0, 0));
    }//GEN-LAST:event_Posicao1ActionPerformed

    public void fim(Boolean jogos) {
        if (jogo.getVez() == 1) {
            jogo.setPontuacaoX(jogo.getPontuacaoO() + 1);
            PontosO.setText(String.valueOf(jogo.getPontuacaoO()));
        } else {
            jogo.setPontuacaoO(jogo.getPontuacaoO() + 1);
            PontosX.setText(String.valueOf(jogo.getPontuacaoO()));

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel PontosO;
    private javax.swing.JLabel PontosX;
    private javax.swing.JButton Posicao1;
    private javax.swing.JButton Posicao2;
    private javax.swing.JButton Posicao3;
    private javax.swing.JButton Posicao4;
    private javax.swing.JButton Posicao5;
    private javax.swing.JButton Posicao6;
    private javax.swing.JButton Posicao7;
    private javax.swing.JButton Posicao8;
    private javax.swing.JButton Posicao9;
    private javax.swing.JButton Voltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
